// Generated by 'unplugin-auto-import'
// @ts-ignore

export {}
declare global {
  const computed: typeof import('vue')['computed']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  }
}